# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c14b3fd764e118d4cdaa2e3c75ae2bcda0bb86f29ec2c678773b8240d5a58041b0cf40a2e53f08d195ad5caa8b8b7b7a1ed7aa84770e020fedf000bb1702ddd

test:
  secret_key_base: 0c91b6a84bdfbaab997aa9e9b3b7477ba066279ece97b11112a10023bcc7d0dfa7bc9482fccb2c0cd2ccbedda25e4c3109de55bd080b43b8a8525bfdd0d6b1a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
